
const SUPABASE_URL="https://wybgqdreqylrojdxijey.supabase.co";const SUPABASE_ANON_KEY="sb_publishable_9WipqtAt_5CwaKdc1hbPOA_0O43S7go";const supa=supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
let cache={clientes:[],servicos:[],orcamentos:[],os:[],termos:[]};
let headerConfig=JSON.parse(localStorage.getItem('mp_header')||'{"nome":"Manoel Pedra Construção e Reforma","desc":"Construção, Reforma, Elétrica, Hidráulica, Montagem e Instalação","email":"","tel":"","cnpj":"","end":"","logo":""}');
const DEFAULT_CHECK=["Pintura OK","Elétrica OK","Hidráulica OK","Piso/Revestimento OK","Limpeza final OK","Portas/Janelas OK","Metais/Louças OK"];
function toast(m){const t=document.getElementById('toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',3000);}
document.querySelectorAll('.tab').forEach(b=>{b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('tab-'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='hist') carregarHistorico();}});
function initHeader(){document.getElementById('h_logo').value=headerConfig.logo||"";document.getElementById('h_nome').value=headerConfig.nome||"";document.getElementById('h_desc').value=headerConfig.desc||"";document.getElementById('h_email').value=headerConfig.email||"";document.getElementById('h_tel').value=headerConfig.tel||"";document.getElementById('h_cnpj').value=headerConfig.cnpj||"";document.getElementById('h_end').value=headerConfig.end||"";updateHeader();initChecklist();}
function updateHeader(){headerConfig={logo:document.getElementById('h_logo').value,nome:document.getElementById('h_nome').value,desc:document.getElementById('h_desc').value,email:document.getElementById('h_email').value,tel:document.getElementById('h_tel').value,cnpj:document.getElementById('h_cnpj').value,end:document.getElementById('h_end').value};localStorage.setItem('mp_header',JSON.stringify(headerConfig));const p=document.getElementById('headerPreview');let html="";if(headerConfig.logo) html+=`<img src="${headerConfig.logo}" onerror="this.style.display='none'">`;html+=`<div><b>${headerConfig.nome||"Nome da empresa"}</b><br><small>${headerConfig.desc||""}</small><br><small>`;if(headerConfig.email) html+=`${headerConfig.email} | `;if(headerConfig.tel) html+=`${headerConfig.tel} | `;if(headerConfig.end) html+=`${headerConfig.end}`;html+=`</small>`;if(headerConfig.cnpj) html+=`<br><small>CNPJ: ${headerConfig.cnpj}</small>`;html+=`</div>`;p.innerHTML=html;}
function initChecklist(){document.getElementById('checklist').innerHTML=DEFAULT_CHECK.map(txt=>`<label class="check"><input type="checkbox" value="${txt}" checked> ${txt}</label>`).join('');}
initHeader();
async function carregarCache(){try{const [cli,serv,orc,osList,termos]=await Promise.all([supa.from('clientes').select('*').order('created_at',{ascending:false}).limit(100),supa.from('servicos_catalogo').select('*').limit(100),supa.from('orcamentos').select('*').order('created_at',{ascending:false}).limit(100),supa.from('ordens_servico').select('*').order('created_at',{ascending:false}).limit(100),supa.from('termos_entrega').select('*').order('created_at',{ascending:false}).limit(100)]);cache.clientes=cli.data||[];cache.servicos=serv.data||[];cache.orcamentos=orc.data||[];cache.os=osList.data||[];cache.termos=termos.data||[];}catch(e){console.log(e);}}
carregarCache();
function attachAC(inputId,listId,getItems,onSelect){const inp=document.getElementById(inputId);const list=document.getElementById(listId);if(!inp)return;inp.addEventListener('input',()=>{const q=inp.value.toLowerCase().trim();if(q.length<1){list.style.display='none';return;}const items=getItems(q).slice(0,6);if(!items.length){list.style.display='none';return;}list.innerHTML=items.map(it=>`<div data-v='${encodeURIComponent(JSON.stringify(it))}'>${it._label}</div>`).join('');list.style.display='block';list.querySelectorAll('div').forEach(d=>{d.onclick=()=>{const obj=JSON.parse(decodeURIComponent(d.dataset.v));onSelect(obj);list.style.display='none';};});});document.addEventListener('click',(e)=>{if(!e.target.closest('#'+inputId)&&!e.target.closest('#'+listId))list.style.display='none';});}
attachAC('orc_cliente_nome','ac_cliente_nome',q=>{const fromCli=cache.clientes.filter(c=>c.nome.toLowerCase().includes(q)).map(c=>({...c,_label:`<b>${c.nome}</b> <small>${c.telefone||''} - ${c.endereco||''}</small>`}));const fromOrc=cache.orcamentos.filter(o=>(o.cliente_nome||'').toLowerCase().includes(q)).map(o=>({...o,_label:`<b>${o.cliente_nome}</b> <small>orc: ${o.tipo_servico||''}</small>`}));return [...fromCli,...fromOrc];},obj=>{if(obj.nome){document.getElementById('orc_cliente_nome').value=obj.nome;document.getElementById('orc_cliente_tel').value=obj.telefone||'';document.getElementById('orc_cliente_end').value=obj.endereco||'';document.getElementById('orc_cliente_cnpj').value=obj.cnpj||'';}else{document.getElementById('orc_cliente_nome').value=obj.cliente_nome;document.getElementById('orc_cliente_tel').value=obj.cliente_telefone||'';document.getElementById('orc_cliente_end').value=obj.cliente_endereco||'';document.getElementById('orc_cliente_cnpj').value=obj.cliente_cnpj||'';if(obj.itens&&confirm('Puxar itens do orçamento anterior de '+obj.cliente_nome+'?')){carregarItensDe(obj.itens);}}});
attachAC('orc_cliente_end','ac_end',q=>{const ends=[...new Set([...cache.clientes.map(c=>c.endereco),...cache.orcamentos.map(o=>o.cliente_endereco)].filter(Boolean))];return ends.filter(e=>e.toLowerCase().includes(q)).map(e=>({_label:e,_val:e}));},obj=>{document.getElementById('orc_cliente_end').value=obj._val;});
function addItem(pref={}){const cont=document.getElementById('itensContainer');const div=document.createElement('div');div.className='item-row';div.innerHTML=`<div class="field autocomplete-wrap"><label>Serviço / Material</label><input class="it-nome" placeholder="Ex: reboco" value="${pref.nome||''}"><div class="ac-list"></div></div><div class="field"><label>Un</label><input class="it-un" value="${pref.unidade||'m²'}"></div><div class="field"><label>Qtd</label><input class="it-qtd" type="number" value="${pref.qtd||1}" oninput="calcTotal()"></div><div class="field"><label>Mão obra</label><input class="it-mo" type="number" value="${pref.preco_mao_obra||0}" oninput="calcTotal()"></div><div class="field"><label>Material</label><input class="it-mat" type="number" value="${pref.preco_material||0}" oninput="calcTotal()"></div><button onclick="this.parentElement.remove();calcTotal()" style="border:none;background:#fee2e2;border-radius:8px;cursor:pointer">✕</button>`;cont.appendChild(div);const inp=div.querySelector('.it-nome');const ac=div.querySelector('.ac-list');inp.addEventListener('input',()=>{const q=inp.value.toLowerCase();if(q.length<1){ac.style.display='none';return;}const servs=cache.servicos.filter(s=>s.nome.toLowerCase().includes(q));const old=[];cache.orcamentos.forEach(o=>{(o.itens||[]).forEach(it=>{if((it.nome||'').toLowerCase().includes(q)) old.push(it);});});const all=[...servs.map(s=>({_label:`<b>${s.nome}</b> <small>${s.especialidade} MO:${s.preco_mao_obra} MAT:${s.preco_material}</small>`,_src:s})),...old.map(it=>({_label:`<b>${it.nome}</b> <small>usado</small>`,_src:it}))].slice(0,6);if(!all.length){ac.style.display='none';return;}ac.innerHTML=all.map(a=>`<div>${a._label}</div>`).join('');ac.style.display='block';ac.querySelectorAll('div').forEach((d,i)=>{d.onclick=()=>{const src=all[i]._src;div.querySelector('.it-nome').value=src.nome;div.querySelector('.it-un').value=src.unidade||'m²';div.querySelector('.it-mo').value=src.preco_mao_obra||0;div.querySelector('.it-mat').value=src.preco_material||0;ac.style.display='none';calcTotal();};});});calcTotal();}
function carregarItensDe(itens){document.getElementById('itensContainer').innerHTML='';itens.forEach(it=>addItem(it));calcTotal();}
function calcTotal(){let total=0;document.querySelectorAll('.item-row').forEach(row=>{const qtd=parseFloat(row.querySelector('.it-qtd').value)||0;const mo=parseFloat(row.querySelector('.it-mo').value)||0;const mat=parseFloat(row.querySelector('.it-mat').value)||0;total+=(qtd*(mo+mat));});document.getElementById('orc_total').textContent='R$ '+total.toLocaleString('pt-BR',{minimumFractionDigits:2});return total;}
addItem();
// APENAS AO SALVAR VAI PRO BANCO
async function salvarOrcamento(){const itens=[];document.querySelectorAll('.item-row').forEach(r=>{itens.push({nome:r.querySelector('.it-nome').value,unidade:r.querySelector('.it-un').value,qtd:parseFloat(r.querySelector('.it-qtd').value)||0,preco_mao_obra:parseFloat(r.querySelector('.it-mo').value)||0,preco_material:parseFloat(r.querySelector('.it-mat').value)||0});});const payload={cliente_nome:document.getElementById('orc_cliente_nome').value,cliente_telefone:document.getElementById('orc_cliente_tel').value,cliente_endereco:document.getElementById('orc_cliente_end').value,cliente_cnpj:document.getElementById('orc_cliente_cnpj').value,especialidade:document.getElementById('orc_especialidade').value,tipo_servico:document.getElementById('orc_tipo_serv').value,prazo:document.getElementById('orc_prazo').value,forma_pagamento:document.getElementById('orc_pagto').value,itens:itens,total:calcTotal(),observacoes:document.getElementById('orc_obs').value,anexos:(document.getElementById('orc_anexos').value||'').split('\n').filter(Boolean),codigo_govbr:document.getElementById('orc_govbr').value,link_nfse:document.getElementById('orc_nfse').value,link_app:document.getElementById('orc_app').value,header_config:headerConfig};if(!payload.cliente_nome){alert('Digite cliente');return;}const {error}=await supa.from('orcamentos').insert([payload]);if(error){alert(error.message);return;}await supa.from('clientes').insert([{nome:payload.cliente_nome,telefone:payload.cliente_telefone,endereco:payload.cliente_endereco,cnpj:payload.cliente_cnpj}]);toast('Orçamento salvo no banco! ✅');await carregarCache();}
attachAC('os_busca_orc','ac_orc',q=>cache.orcamentos.filter(o=>(o.cliente_nome||'').toLowerCase().includes(q)).map(o=>({...o,_label:`<b>${o.cliente_nome}</b> - ${o.tipo_servico} - R$${o.total}`})),obj=>{document.getElementById('os_busca_orc').value=obj.cliente_nome+' - '+obj.tipo_servico;document.getElementById('os_cliente').value=obj.cliente_nome;document.getElementById('os_end').value=obj.cliente_endereco;document.getElementById('os_escopo').value=(obj.itens||[]).map(i=>`${i.nome} - ${i.qtd}${i.unidade}`).join('\n');document.getElementById('os_valor').value=obj.total;document.getElementById('os_cliente').dataset.orcId=obj.id;});
async function salvarOS(){const payload={orcamento_id:document.getElementById('os_cliente').dataset.orcId||null,cliente_nome:document.getElementById('os_cliente').value,obra_endereco:document.getElementById('os_end').value,escopo:document.getElementById('os_escopo').value,data_inicio:document.getElementById('os_inicio').value||null,prazo:document.getElementById('os_prazo').value,equipe:document.getElementById('os_equipe').value,valor:parseFloat(document.getElementById('os_valor').value)||0,anexos:(document.getElementById('os_anexos').value||'').split('\n').filter(Boolean),codigo_govbr:document.getElementById('os_govbr').value,header_config:headerConfig};const {error}=await supa.from('ordens_servico').insert([payload]);if(error){alert(error.message);return;}toast('OS salva! ✅');carregarCache();}
attachAC('termo_busca_os','ac_os',q=>cache.os.filter(o=>(o.cliente_nome||'').toLowerCase().includes(q)).map(o=>({...o,_label:`<b>${o.cliente_nome}</b> - ${o.escopo?.slice(0,40)}`})),obj=>{document.getElementById('termo_busca_os').value=obj.cliente_nome;document.getElementById('termo_cliente').value=obj.cliente_nome;document.getElementById('termo_end').value=obj.obra_endereco;document.getElementById('termo_cliente').dataset.osId=obj.id;});
async function salvarTermo(){const checklist=[...document.querySelectorAll('#checklist input:checked')].map(i=>i.value);const payload={os_id:document.getElementById('termo_cliente').dataset.osId||null,cliente_nome:document.getElementById('termo_cliente').value,obra_endereco:document.getElementById('termo_end').value,checklist:checklist,observacoes:document.getElementById('termo_obs').value,data_entrega:document.getElementById('termo_data').value||null,codigo_govbr:document.getElementById('termo_govbr').value,anexos:(document.getElementById('termo_anexos').value||'').split('\n').filter(Boolean),header_config:headerConfig};const {error}=await supa.from('termos_entrega').insert([payload]);if(error){alert(error.message);return;}toast('Termo salvo! ✅');carregarCache();}
function buscaGlobal(){const q=(document.getElementById('busca_global').value||'').toLowerCase();carregarHistorico(q);}
async function carregarHistorico(filtro=''){const f=filtro.toLowerCase();function filter(arr,fields){if(!f)return arr.slice(0,20);return arr.filter(o=>fields.some(k=>String(o[k]||'').toLowerCase().includes(f)||JSON.stringify(o.itens||'').toLowerCase().includes(f))).slice(0,20);}const orcs=filter(cache.orcamentos,['cliente_nome','cliente_endereco','tipo_servico','especialidade']);const osL=filter(cache.os,['cliente_nome','obra_endereco','escopo']);const termos=filter(cache.termos,['cliente_nome','obra_endereco']);document.getElementById('hist_orc').innerHTML=orcs.map(o=>`<div class="hist-item"><b>${o.cliente_nome}</b> - ${o.tipo_servico||''} - R$${o.total}<small>${o.cliente_endereco||''} | ${new Date(o.created_at).toLocaleDateString()}</small><small>Gov: ${o.codigo_govbr||'-'}</small><div style="margin-top:6px"><button class="btn-outline" onclick='reusarOrc("${o.id}")'>♻️ Reusar</button></div></div>`).join('')||'<small>Nenhum</small>';document.getElementById('hist_os').innerHTML=osL.map(o=>`<div class="hist-item"><b>${o.cliente_nome}</b><small>${o.obra_endereco} - ${o.prazo}</small></div>`).join('')||'<small>Nenhum</small>';document.getElementById('hist_termo').innerHTML=termos.map(o=>`<div class="hist-item"><b>${o.cliente_nome}</b><small>${o.obra_endereco} - ${o.data_entrega||''}</small></div>`).join('')||'<small>Nenhum</small>';}
function reusarOrc(id){const o=cache.orcamentos.find(x=>x.id===id);if(!o)return;document.querySelector('[data-tab="orc"]').click();document.getElementById('orc_cliente_nome').value=o.cliente_nome;document.getElementById('orc_cliente_tel').value=o.cliente_telefone||'';document.getElementById('orc_cliente_end').value=o.cliente_endereco||'';document.getElementById('orc_cliente_cnpj').value=o.cliente_cnpj||'';document.getElementById('orc_especialidade').value=o.especialidade||'';document.getElementById('orc_tipo_serv').value=o.tipo_servico||'';carregarItensDe(o.itens||[]);toast('Dados puxados do banco! Edite e salve como novo.');}
